
ChatPhrases["lol"] 		= { "It's funny, isn't it.", "Thats not funny...", "Hahaha." }
ChatPhrases["lol?"] 	= { "What?", "Thats not funny...", "Are you mocking me?" }
ChatPhrases["rofl"] 	= { "It's funny, isn't it.", "Thats not funny...", "Hahaha." }
ChatPhrases["lmao"] 	= { "It's funny, isn't it.", "Thats not funny...", "Hahaha." }
ChatPhrases["shhh"] 	= { "Don't you shush me!" }
ChatPhrases["fuck"]		= { "Don't swear please, it will make your teeth fall out!", "You never know, I might be your mother , so don't swear XD ." }
ChatPhrases["why?"] 	= { "'Why?' is not proper grammar!", "Why what?" }
ChatPhrases["what?"] 	= { "Nothing ...", "I didn't say anything ..." }
ChatPhrases["what"]		= { "Nothing ...", "Yep." }
ChatPhrases["sugar"] 	= { "Sugar is sweet and so is choclate!!", "I love sugar :D." }
ChatPhrases[":d"] 		= { "<n> seems happy today!", "You seem happy today!" }
ChatPhrases[":)"] 		= { "You seem happy today!" }
ChatPhrases[":("] 		= { "What's wrong?" }
ChatPhrases["d:"] 		= { "What's wrong?", "Haha <n> got a scare for a lifetime" }
ChatPhrases["xd"] 		= { "xD", "LOL." }
ChatPhrases["nothing"] 	= { "Nothing is everything that isn't known yet ..." }
ChatPhrases["anything"]	= { "Anything is the things that are all around us ...." }
ChatPhrases["up"] 		= { "The sky is up :D and so are the birds!" }
ChatPhrases["up?"] 		= { "The sky is up :D and so are the birds!" }
ChatPhrases["no"] 		= { "meh" }
ChatPhrases["cool"] 	= { "Yes, it is cool, but not cold really..." }
ChatPhrases["nick?"] 	= { "Yes?" }
ChatPhrases["yes"] 		= { "Yey!" }
ChatPhrases["yes?"] 	= { "What?", "Yes", "No, not really ;)" }
ChatPhrases["bot"] 		= { "Bots?", "There are no bots.", "Everyone's a bot today!" }
ChatPhrases["damn"]		= { ":)", ":D" } 
